# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: get_genome_annotation
description: Placeholder
keywords:
  - prokka
  - bacterial
  - annotation
components:
  - prokka:
      git_remote: https://github.com/nf-core/modules.git
  - wget
input:
  - reference_tuple:
      description: |
        Placeholder
  - csv_ch:
      description: |
        Placeholder
output:
  - prokka_res:
      description: |
        Placeholder
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@sanger-tol"

