# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core-test/modules/main/subworkflows/yaml-schema.json
name: wget_subwf
description: Dummy subworkflow that only uses nf-core modules. Used to test https://github.com/nf-core/tools/issues/3876
keywords:
  - download
components:
  - wget:
      git_remote: https://github.com/nf-core/modules.git
input:
  - urls:
      description: |
        Placeholder
output:
  - outfile:
      description: |
        Placeholder
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@sanger-tol"

